### ISSUE TITLE
time.sleep too fast, crashes after 100 names (rate limit? idk)

### ISSUE THREAD

**Issue by letterbit** [chaosaudit/twitch_auto_ban#1]
I fixed this by changing line 46 from`time.sleep(0.1)` to `time.sleep(0.4)`, which makes it a significant amount slower, but it stays open while I do other things 👍 I wonder if there's a way to have it stop for a second at 99 or 100 on the banlist and then continue at 0.1?

(oh also tysm for writing this!!!!!! extremely helpful script <3)

edit2: Error message when running below `time.sleep(0.4)` (I realized I should run the command in cmd instead of just double clicking the script 😅):

> Traceback (most recent call last):
>  File "[...]\twitch_auto_ban-main\twitch_auto_ban.py", line 45, in <module> con.send(str.encode(f"PRIVMSG {CHAN.lower()} :/ban {name.strip()} {ban_message}\r\n"))
> ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

**Comment by chaosaudit** [comment]
Thanks! Yeah forgot all about the rate limiting when I uploaded this. It's limited to 100 messages per 30 seconds for a mod so a delay of 0.32 is the fastest I've got it to run with no issues
